import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Use autogenerated sidebars based on the filesystem structure and _category_.json files
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate a sidebar for the docs folder
    },
  ],
};

export default sidebars;