import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Separate sidebar for Behavior docs
  behaviorSidebar: [
    {
      type: 'autogenerated',
      dirName: 'behavior',
    },
  ],

  // Separate sidebar for Backend docs
  backendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'backend',
    },
  ],

  // Separate sidebar for Frontend docs
  frontendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'frontend',
    },
  ],

  // Separate sidebar for Language docs
  languageSidebar: [
    {
      type: 'autogenerated',
      dirName: 'language',
    },
  ],
};

export default sidebars;